import type { RoleKey } from './roles.js';
import { Permission, ALL_PERMISSIONS } from './permissions.js';

/**
 * Default role → permission mapping (the system RBAC baseline), derived from the RBAC matrix
 * in docs/architecture/05-rbac-matrix.md. Seeded per tenant during provisioning (Phase 4) and
 * for platform-plane roles during platform setup. `'*'` means "all permissions".
 *
 * Scoped (row-level) restrictions for roles like Teacher/Parent/Student (e.g. only their own
 * sections/children) are enforced in the service/repository layer, not by the permission set.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, Permission[] | '*'> = {
  // Platform plane
  PlatformOwner: '*',
  PlatformAdmin: [
    Permission.PLATFORM_TENANT_MANAGE,
    Permission.SUPPORT_IMPERSONATE,
    Permission.AUDIT_READ,
    Permission.FEATUREFLAG_MANAGE,
    // Platform Console
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_SUBSCRIPTION_MANAGE,
    Permission.PLATFORM_PLAN_MANAGE,
    Permission.PLATFORM_UPGRADE_REVIEW,
    Permission.PLATFORM_TRIAL_MANAGE,
    Permission.PLATFORM_BILLING_READ,
    Permission.PLATFORM_BILLING_MANAGE,
    Permission.PLATFORM_COUPON_MANAGE,
    Permission.PLATFORM_FEATURE_OVERRIDE,
    Permission.PLATFORM_FEATUREFLAG_MANAGE,
    Permission.PLATFORM_SUPPORT_MANAGE,
    Permission.PLATFORM_AUDIT_READ,
    Permission.PLATFORM_USER_MANAGE,
    Permission.PLATFORM_SYSTEM_HEALTH_READ,
    Permission.PLATFORM_REVENUE_READ,
  ],
  // Platform Finance: subscriptions, billing, coupons, revenue.
  PlatformFinance: [
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_SUBSCRIPTION_MANAGE,
    Permission.PLATFORM_UPGRADE_REVIEW,
    Permission.PLATFORM_BILLING_READ,
    Permission.PLATFORM_BILLING_MANAGE,
    Permission.PLATFORM_COUPON_MANAGE,
    Permission.PLATFORM_REVENUE_READ,
    Permission.PLATFORM_AUDIT_READ,
  ],
  // Platform Support: read-mostly + support ops + impersonation + feature overrides for triage.
  PlatformSupport: [
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_SUPPORT_MANAGE,
    Permission.PLATFORM_FEATURE_OVERRIDE,
    Permission.PLATFORM_AUDIT_READ,
    Permission.PLATFORM_SYSTEM_HEALTH_READ,
    Permission.SUPPORT_IMPERSONATE,
  ],
  // Platform Sales: schools, subscriptions (read), upgrade review, trials, coupons.
  PlatformSales: [
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_UPGRADE_REVIEW,
    Permission.PLATFORM_TRIAL_MANAGE,
    Permission.PLATFORM_COUPON_MANAGE,
  ],
  // Platform Read Only: full visibility, zero mutation.
  PlatformReadOnly: [
    Permission.PLATFORM_DASHBOARD_READ,
    Permission.PLATFORM_SCHOOL_READ,
    Permission.PLATFORM_SUBSCRIPTION_READ,
    Permission.PLATFORM_BILLING_READ,
    Permission.PLATFORM_REVENUE_READ,
    Permission.PLATFORM_AUDIT_READ,
    Permission.PLATFORM_SYSTEM_HEALTH_READ,
  ],
  SupportAgent: [Permission.SUPPORT_IMPERSONATE, Permission.AUDIT_READ],

  // School plane
  SchoolAdmin: '*',
  Principal: [
    Permission.CARD_MANAGE,
    Permission.CARD_READ,
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_READ,
    Permission.ATTENDANCE_CONFIGURE,
    Permission.SCHOOL_MANAGE,
    Permission.CAMPUS_MANAGE,
    Permission.ACADEMICYEAR_MANAGE,
    Permission.GRADE_MANAGE,
    Permission.SECTION_MANAGE,
    Permission.CLASSROOM_MANAGE,
    Permission.ORGANIZATION_READ,
    Permission.TIMETABLE_READ,
    Permission.ATTENDANCE_READ,
    Permission.HOMEWORK_READ,
    Permission.BEHAVIOR_MANAGE,
    Permission.BEHAVIOR_READ,
    Permission.GRADE_READ,
    Permission.ANNOUNCEMENT_MANAGE,
    Permission.NOTIFICATION_SEND,
    Permission.NOTIFICATION_SETTINGS,
    Permission.LEAVE_APPROVE,
    Permission.REPORT_READ,
    Permission.REPORT_EXPORT,
    Permission.AUDIT_READ,
    Permission.FINANCE_READ,
    Permission.SUBSCRIPTION_READ,
    Permission.SUBSCRIPTION_UPGRADE_REQUEST,
    Permission.DOCUMENT_READ,
    Permission.RESOURCE_READ,
    Permission.RESOURCE_MANAGE,
    Permission.ACHIEVEMENT_MANAGE,
    Permission.BUS_READ,
    Permission.LIBRARY_READ,
    Permission.INVENTORY_READ,
    Permission.CLINIC_READ,
  ],
  VicePrincipal: [
    Permission.CARD_READ,
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_READ,
    Permission.ATTENDANCE_CONFIGURE,
    Permission.TIMETABLE_MANAGE,
    Permission.ATTENDANCE_CREATE,
    Permission.ATTENDANCE_READ,
    Permission.BEHAVIOR_MANAGE,
    Permission.BEHAVIOR_READ,
    Permission.HOMEWORK_READ,
    Permission.GRADE_READ,
    Permission.ANNOUNCEMENT_MANAGE,
    Permission.NOTIFICATION_SEND,
    Permission.LEAVE_APPROVE,
    Permission.PTM_MANAGE,
    Permission.REPORT_READ,
    Permission.RESOURCE_READ,
    Permission.RESOURCE_MANAGE,
    Permission.ACHIEVEMENT_MANAGE,
  ],
  FinanceOfficer: [
    Permission.FINANCE_MANAGE,
    Permission.FINANCE_READ,
    Permission.FINANCE_EXPORT,
    Permission.FINANCE_TRANSFER_BILLING, // manager-level: change the legal payer

    Permission.TRANSACTION_CREATE,
    Permission.RECEIPT_UPLOAD,
    Permission.ENROLLMENT_MANAGE,
    Permission.FEE_OVERRIDE,
    Permission.FINANCE_APPROVE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_GENERATE,
    Permission.DOCUMENT_UPLOAD_SIGNED,
    Permission.DOCUMENT_REPLACE_SIGNED,
    Permission.DOCUMENT_DELETE_SIGNED,
    Permission.REPORT_READ,
    Permission.REPORT_EXPORT,
    Permission.AUDIT_READ,
  ],
  // Accountant: finance operations + can register students (per product requirement).
  Accountant: [
    Permission.FINANCE_MANAGE,
    Permission.FINANCE_READ,
    Permission.FINANCE_EXPORT,
    Permission.TRANSACTION_CREATE,
    Permission.RECEIPT_UPLOAD,
    Permission.STUDENT_MANAGE,
    Permission.ENROLLMENT_MANAGE,
    Permission.FEE_OVERRIDE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_GENERATE,
    Permission.DOCUMENT_UPLOAD_SIGNED,
    Permission.DOCUMENT_REPLACE_SIGNED,
    Permission.REPORT_READ,
    Permission.REPORT_EXPORT,
  ],
  Teacher: [
    Permission.CARD_READ,
    Permission.PRESENCE_CREATE,
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_CREATE,
    Permission.TRANSPORT_READ,
    Permission.TIMETABLE_READ,
    Permission.ATTENDANCE_CREATE,
    Permission.ATTENDANCE_READ,
    Permission.HOMEWORK_MANAGE,
    Permission.HOMEWORK_READ,
    Permission.BEHAVIOR_MANAGE,
    Permission.BEHAVIOR_READ,
    Permission.GRADE_IMPORT,
    Permission.GRADE_READ,
    Permission.ANNOUNCEMENT_READ,
    Permission.NOTIFICATION_SEND,
    Permission.REPORT_READ,
    Permission.RESOURCE_READ,
    Permission.RESOURCE_MANAGE,
    Permission.ACHIEVEMENT_MANAGE,
  ],
  Secretary: [
    Permission.CARD_MANAGE,
    Permission.CARD_READ,
    Permission.PRESENCE_CREATE,
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_READ,
    Permission.STUDENT_MANAGE,
    Permission.PARENT_MANAGE,
    Permission.DOCUMENT_MANAGE,
    Permission.ATTENDANCE_READ,
    Permission.ANNOUNCEMENT_READ,
    Permission.TIMETABLE_READ,
    // Advanced modules operations (gated by per-tenant feature flags)
    Permission.BUS_MANAGE,
    Permission.BUS_ASSIGN,
    Permission.BUS_READ,
    Permission.LIBRARY_MANAGE,
    Permission.LIBRARY_READ,
    Permission.INVENTORY_MANAGE,
    Permission.INVENTORY_READ,
    Permission.CLINIC_MANAGE,
    Permission.CLINIC_READ,
  ],
  // Receptionist: front-desk — sends announcements/notifications, reads attendance, manages docs.
  Receptionist: [
    Permission.PRESENCE_CREATE,
    Permission.PRESENCE_READ,
    Permission.ANNOUNCEMENT_MANAGE,
    Permission.NOTIFICATION_SEND,
    Permission.ATTENDANCE_READ,
    Permission.CARD_READ,
    Permission.DOCUMENT_MANAGE,
  ],
  // Registrar: student/parent records, admissions, quotations and fee overrides.
  Registrar: [
    Permission.STUDENT_MANAGE,
    Permission.PARENT_MANAGE,
    Permission.DOCUMENT_MANAGE,
    Permission.ENROLLMENT_MANAGE,
    Permission.FEE_OVERRIDE,
    Permission.FINANCE_READ,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_GENERATE,
    Permission.DOCUMENT_UPLOAD_SIGNED,
    Permission.DOCUMENT_REPLACE_SIGNED,
    Permission.DOCUMENT_DELETE_SIGNED,
    Permission.REPORT_READ,
  ],
  // Counselor: behaviour & achievements, reads attendance.
  Counselor: [
    Permission.BEHAVIOR_MANAGE,
    Permission.BEHAVIOR_READ,
    Permission.ATTENDANCE_READ,
    Permission.ACHIEVEMENT_MANAGE,
  ],
  // HR: staff records & leave approvals.
  HR: [Permission.EMPLOYEE_MANAGE, Permission.TEACHER_MANAGE, Permission.LEAVE_APPROVE],
  // Nurse: clinic module + attendance visibility.
  Nurse: [Permission.CLINIC_MANAGE, Permission.CLINIC_READ, Permission.ATTENDANCE_READ],
  // Librarian: library module.
  Librarian: [Permission.LIBRARY_MANAGE, Permission.LIBRARY_READ],
  // StoreKeeper: inventory module.
  StoreKeeper: [Permission.INVENTORY_MANAGE, Permission.INVENTORY_READ],
  // FleetAdmin: configures buses/routes and assigns students (gated by bus_tracking).
  FleetAdmin: [
    Permission.BUS_MANAGE,
    Permission.BUS_ASSIGN,
    Permission.BUS_READ,
    Permission.TRANSPORT_READ,
    Permission.CARD_READ,
  ],
  // BusSupervisor: on-board boarding/alighting scans.
  BusSupervisor: [
    Permission.TRANSPORT_CREATE,
    Permission.TRANSPORT_READ,
    Permission.CARD_READ,
    Permission.BUS_READ,
    Permission.PRESENCE_READ,
  ],
  Parent: [
    Permission.PRESENCE_READ,
    Permission.TRANSPORT_READ,
    Permission.ATTENDANCE_READ,
    Permission.HOMEWORK_READ,
    Permission.BEHAVIOR_READ,
    Permission.GRADE_READ,
    Permission.TIMETABLE_READ,
    Permission.ANNOUNCEMENT_READ,
    Permission.RECEIPT_UPLOAD,
    Permission.FINANCE_READ,
    Permission.LEAVE_REQUEST,
    Permission.PTM_BOOK,
    Permission.DOCUMENT_MANAGE,
    Permission.RESOURCE_READ,
    Permission.ACHIEVEMENT_READ,
    Permission.GAMIFICATION_READ,
  ],
  Student: [
    Permission.ATTENDANCE_READ,
    Permission.HOMEWORK_READ,
    Permission.BEHAVIOR_READ,
    Permission.GRADE_READ,
    Permission.TIMETABLE_READ,
    Permission.ANNOUNCEMENT_READ,
    Permission.RESOURCE_READ,
    Permission.ACHIEVEMENT_READ,
    Permission.GAMIFICATION_READ,
  ],
};

/** Resolve the concrete permission set for a role (expanding `'*'`). */
export function permissionsForRole(role: RoleKey): Permission[] {
  const mapped = DEFAULT_ROLE_PERMISSIONS[role];
  return mapped === '*' ? [...ALL_PERMISSIONS] : mapped;
}
